apiVersion: v1
kind: Service

metadata:
  name: passin-service
  labels:
    app: passin

spec:
  type: ClusterIP

  selector:
    app: passin
  ports:
  - name: passin-service
    port: 80
    targetPort: 3333
    protocol: TCP